### PR TITLE
Fix TINYINT buffer issue

### PR DESCRIPTION
**Pull request by collinhundley**
Fixes an issue that occurs while reading TINYINT values from the buffer.

See #31

### CODE REVIEW

**Comment by tannernelson** [comment]
Can we include a test with this to make sure it's good on Linux + macOS?

**Comment by tannernelson** [comment]
@collinhundley can you update your branch with master or move to a branch on this repo?

**Comment by collinhundley** [comment]
Yep, but I'll need to do it tomorrow unfortunately. Feel free to pester me
if I forget for some reason.

**Comment by tannernelson** [comment]
Lol sounds good.

**Comment by collinhundley** [comment]
Trying to sync my branch but having some Swift version issues. It looks like Node has been updated to 8-18, so what are the chances we can update this one too? Most of my stuff is on 8-23 but 8-18 would probably be close enough.

**Comment by kylerokita** [comment]
Was running into problems with MySQL booleans and it was driving me a little crazy. Thanks for figuring this out.

In case you are curious, I could recreate this issue in both Linux and Mac when using ```vapor build --mysql```. However, building from Xcode always worked as expected.

**Pull request merged**
