### PR TITLE
fixed typo in comment

### PR DESCRIPTION
**Pull request by ditansu**

### CODE REVIEW

**Comment by 0xTim** [comment]
This PR should be addressed by #146

**Comment by ditansu** [comment]
> This PR should be addressed by #146

sure, but I do not have enough rights for this

```shell
git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree push -v origin refs/heads/mysql-default-port:refs/heads/mysql-default-port 
Pushing to https://github.com/vapor/mysql.git
remote: Permission to vapor/mysql.git denied to ditansu.
fatal: unable to access 'https://github.com/vapor/mysql.git/': The requested URL returned error: 403
Completed with errors, see above
```

**Comment by 0xTim** [comment]
Sorry I should have been clearer! It has been fixed in https://github.com/vapor/mysql/pull/146/files#diff-e53602c5f123d3da5b227a2b208fac81R3

**Comment by ditansu** [comment]
ok, fine!

**Pull request closed without merging**
